import pytest

from research_engine.connectors import web
from research_engine.models import CollectionRequest
from research_engine.targets import ResearchTarget, classify_target_evidence


@pytest.mark.parametrize(
    "url",
    [
        "http://127.0.0.1/private",
        "http://localhost/private",
        "http://169.254.169.254/latest/meta-data",
        "http://user:password@example.com/private",
        "file:///etc/passwd",
    ],
)
def test_fetch_page_rejects_non_public_or_credentialed_urls_before_transport(url):
    with pytest.raises(ValueError, match="public|credentials|scheme"):
        web.fetch_page(url)


def test_redirect_handler_rejects_private_redirect_before_following():
    handler = web.PublicRedirectHandler()

    with pytest.raises(ValueError, match="public"):
        handler.redirect_request(
            None,
            None,
            302,
            "Found",
            {},
            "http://127.0.0.1/private",
        )


class FakeResponse:
    def __init__(self, *, body: bytes, final_url: str):
        self.body = body
        self.final_url = final_url

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def read(self, limit):
        return self.body[:limit]

    def geturl(self):
        return self.final_url


class FakeOpener:
    def __init__(self, response):
        self.response = response

    def open(self, request, timeout):
        return self.response


def test_fetch_page_bounds_response_body(monkeypatch):
    response = FakeResponse(
        body=b"x" * (web.MAX_RESPONSE_BYTES + 1),
        final_url="https://93.184.216.34/job/123",
    )
    monkeypatch.setattr(web, "build_opener", lambda *handlers: FakeOpener(response))

    with pytest.raises(ValueError, match="response body exceeds"):
        web.fetch_page("https://93.184.216.34/job/123")


def test_fetch_page_revalidates_final_redirect_url(monkeypatch):
    response = FakeResponse(
        body=b"<html><body>public start</body></html>",
        final_url="http://127.0.0.1/private",
    )
    monkeypatch.setattr(web, "build_opener", lambda *handlers: FakeOpener(response))

    with pytest.raises(ValueError, match="public"):
        web.fetch_page("https://93.184.216.34/start")


@pytest.mark.parametrize(
    ("body", "expected"),
    [
        ("You've been blocked by network security.", "access_blocked"),
        (
            "403 ERROR The request could not be satisfied. Request blocked. Generated by cloudfront.",
            "access_blocked",
        ),
        ("Loading… Powered by Ashby", "javascript_shell"),
        ("Page not found", "not_found_or_closed"),
        ("This job is no longer available.", "not_found_or_closed"),
    ],
)
def test_page_body_status_rejects_blocked_shell_and_closed_bodies(body, expected):
    assert web.page_body_status(body) == expected


def test_page_body_status_does_not_reject_substantive_job_text():
    text = (
        "Staff Software Engineer. Build the request blocking service used by our "
        "customers. You will design APIs, review code, and operate production systems. "
    ) * 4

    assert web.page_body_status(text) == "usable"


@pytest.mark.parametrize(
    "body",
    [
        "You've been blocked by network security.",
        "403 ERROR The request could not be satisfied. Request blocked. Generated by cloudfront.",
        "Loading... Powered by Ashby",
        "Page not found",
        "This position has been closed.",
    ],
)
def test_fetch_page_does_not_return_unusable_body(monkeypatch, body):
    response = FakeResponse(
        body=f"<html><body>{body}</body></html>".encode(),
        final_url="https://93.184.216.34/job/123",
    )
    monkeypatch.setattr(web, "build_opener", lambda *handlers: FakeOpener(response))
    monkeypatch.setattr(web, "_fetch_playwright", lambda *args, **kwargs: (body, args[0]))

    assert web.fetch_page("https://93.184.216.34/job/123") == ("", "")


def test_status_fetch_preserves_closed_body_for_upstream_api_fallback_gate(monkeypatch):
    body = "This job is no longer available."
    url = "https://93.184.216.34/job/123"
    response = FakeResponse(
        body=f"<html><body>{body}</body></html>".encode(),
        final_url=url,
    )
    monkeypatch.setattr(web, "build_opener", lambda *handlers: FakeOpener(response))
    monkeypatch.setattr(web, "_fetch_playwright", lambda *args, **kwargs: ("", ""))

    assert web.fetch_page_with_status(url) == (body, url, "not_found_or_closed")


@pytest.mark.parametrize(
    ("body", "access_blocked", "current_status"),
    [
        ("You've been blocked by network security.", True, "unknown"),
        ("Loading... Powered by Ashby", False, "unknown"),
        ("Page not found", False, "closed"),
    ],
)
def test_connector_marks_unusable_bodies_non_final(
    monkeypatch,
    body,
    access_blocked,
    current_status,
):
    monkeypatch.setattr(
        web,
        "fetch_page_with_status",
        lambda url: (body, url, web.page_body_status(body)),
    )
    request = CollectionRequest(
        source={
            "source_id": "target_discovery_refetch",
            "pages": [{"url": "https://example.com/job/123"}],
        },
        topic="",
        run_date="2026-07-14",
        depth="fast",
        max_results=1,
    )

    row = web.WebPageConnector().collect(request).rows[0]

    assert row["is_final_page"] is False
    assert row["access_blocked"] is access_blocked
    assert row["current_status"] == current_status


@pytest.mark.parametrize(
    ("body", "fetch_status", "access_blocked", "current_status"),
    [
        (
            "403 ERROR The request could not be satisfied. Request blocked. Generated by cloudfront.",
            "access_blocked",
            True,
            "unknown",
        ),
        ("Page not found", "not_found_or_closed", False, "closed"),
    ],
)
def test_target_refetch_propagates_real_transport_body_status(
    monkeypatch,
    body,
    fetch_status,
    access_blocked,
    current_status,
):
    url = "https://93.184.216.34/job/123"
    response = FakeResponse(
        body=f"<html><body>{body}</body></html>".encode(),
        final_url=url,
    )
    monkeypatch.setattr(web, "build_opener", lambda *handlers: FakeOpener(response))
    monkeypatch.setattr(web, "_fetch_playwright", lambda *args, **kwargs: ("", ""))
    request = CollectionRequest(
        source={
            "source_id": "target_discovery_refetch",
            "pages": [{"url": url, "source_kind": "official_job_posting"}],
        },
        topic="",
        run_date="2026-07-14",
        depth="fast",
        max_results=1,
    )

    row = web.WebPageConnector().collect(request).rows[0]

    assert row["text"] == body
    assert row["fetch_status"] == fetch_status
    assert row["is_final_page"] is False
    assert row["access_blocked"] is access_blocked
    assert row["current_status"] == current_status


def test_target_refetch_keeps_bounded_head_and_location_tail_for_amazon(monkeypatch):
    url = "https://www.amazon.jobs/en/jobs/123/software-development-engineer-ii"
    head = (
        "Amazon Software Development Engineer II. Responsibilities and basic qualifications "
        "include distributed systems and API design. "
    )
    body = head + ("Benefits and team information. " * 300) + (
        "Job details: USA, WA, Seattle. Country code: US. Apply now."
    )
    monkeypatch.setattr(
        web,
        "fetch_page_with_status",
        lambda _url: (body, url, "usable"),
    )
    request = CollectionRequest(
        source={
            "source_id": "target_discovery_refetch",
            "pages": [
                {
                    "url": url,
                    "company": "Amazon",
                    "source_kind": "official_job_posting",
                    "current_status": "unknown",
                }
            ],
        },
        topic="Amazon SDE II US",
        run_date="2026-07-14",
        depth="audit",
        max_results=1,
    )

    fetched = web.WebPageConnector().collect(request).rows[0]
    target = ResearchTarget.from_mapping(
        {
            "company": "Amazon",
            "role_family": "software_engineering",
            "role_title": "Software Development Engineer II",
            "level": "SDE II",
            "geography": "US",
        }
    )
    classified = classify_target_evidence(
        [fetched], target=target, run_date="2026-07-14"
    )[0]

    assert len(fetched["text"]) <= web.EVIDENCE_TEXT_CHARS
    assert fetched["text"].startswith("Amazon Software Development Engineer II")
    assert "USA, WA, Seattle" in fetched["text"]
    assert classified["target_match"]["geography"] == "compatible"
    assert classified["current_status"] == "active"
    assert classified["claim_fitness"]["eligible_claims"] == ["current_official_role"]


def test_google_apply_in_omitted_middle_sets_active_before_sampling(monkeypatch):
    url = (
        "https://www.google.com/about/careers/applications/jobs/results/123-"
        "software-engineer-iii-infrastructure"
    )
    heading = "Software Engineer III, Infrastructure"
    global_results = (
        f"{heading} — Google Careers Jobs search results 3,369 jobs matched "
        "Unrelated role Seattle, WA, USA. "
    )
    detail = (
        f"{heading} London, UK. Minimum qualifications and responsibilities. "
        + ("Detailed engineering requirement. " * 120)
        + "Apply now. "
        + ("Equal opportunity information. " * 120)
    )
    body = global_results + ("Other search result. " * 300) + detail
    monkeypatch.setattr(
        web,
        "fetch_page_with_status",
        lambda _url: (body, url, "usable"),
    )
    request = CollectionRequest(
        source={
            "source_id": "target_discovery_refetch",
            "pages": [
                {
                    "url": url,
                    "company": "Google",
                    "source_kind": "official_job_posting",
                    "current_status": "unknown",
                }
            ],
        },
        topic="Google L4 Software Engineer US",
        run_date="2026-07-14",
        depth="audit",
        max_results=1,
    )

    row = web.WebPageConnector().collect(request).rows[0]

    assert "Apply now" not in row["text"]
    assert row["current_status"] == "active"
    assert row["status_inferred_from"] == "full_target_detail"


def test_google_target_detail_location_ignores_unrelated_us_search_results(monkeypatch):
    url = (
        "https://www.google.com/about/careers/applications/jobs/results/123-"
        "software-engineer-iii-infrastructure"
    )
    heading = "Software Engineer III, Infrastructure"
    body = (
        f"{heading} — Google Careers Jobs search results 3,369 jobs matched "
        "Manufacturing Engineer Sunnyvale, CA, USA. Account Manager Seattle, WA, USA. "
        + ("Other global search result. " * 250)
        + f"{heading} London, UK. Minimum qualifications and responsibilities for Google "
        "infrastructure. Apply now."
    )
    monkeypatch.setattr(
        web,
        "fetch_page_with_status",
        lambda _url: (body, url, "usable"),
    )
    request = CollectionRequest(
        source={
            "source_id": "target_discovery_refetch",
            "pages": [
                {
                    "url": url,
                    "company": "Google",
                    "source_kind": "official_job_posting",
                    "current_status": "unknown",
                }
            ],
        },
        topic="Google L4 Software Engineer US",
        run_date="2026-07-14",
        depth="audit",
        max_results=1,
    )
    row = web.WebPageConnector().collect(request).rows[0]
    target = ResearchTarget.from_mapping(
        {
            "company": "Google",
            "role_family": "software_engineering",
            "role_title": "Software Engineer",
            "level": "L4",
            "geography": "US",
        }
    )
    classified = classify_target_evidence(
        [row], target=target, run_date="2026-07-14"
    )[0]

    assert row["page_heading"] == heading
    assert row["text"].startswith(heading + " London, UK")
    assert classified["target_match"]["geography"] == "mismatch"
    assert classified["claim_fitness"]["eligible_claims"] == []
